### ISSUE TITLE
migration to class system on telebot

### ISSUE THREAD

**Issue by slowy07** [dydrmr5/telegramBot#7]
update telebot jole untuk kedepan nya menurut ak joel :
 - delete ```menu_reply.py```
 - rename ```peribahasa.py``` to ```configuration.py``` atau bisa juga pilhan dibawah:
   - ```telebot_configuration.py```
   - ```data.py```
   - ```telebot_data.py```
   - ```config.py```
- rebase all code from ```menu_reply.py``` to ```peribahasa.py``` yang sudah di rename atau namanya tetap
- rebase all code from ```emojis.py``` to ```peribahasa.py``` yang sudah di rename atau namanya tetap

tambahan lain yang kemungkinan juga untuk di update
- reformat atau merapikan lagi coding telebot
- lebih banyak tambahan emoji
- reformat atau merapikan lagi [README.md](https://github.com/ctrlbzul/telegramBot#readme)

untuk selebihnya nanti dikasih checkmark jika update telebot ada yang sudah diselesaikan

**Comment by slowy07** [comment]
## update feature
- [x] reformat atau merapikan [```README.md```](https://github.com/ctrlbzul/telegramBot#readme)

**Comment by dydrmr5** [comment]
-[x]

**Comment by dydrmr5** [comment]
update telebot jole untuk kedepan nya menurut ak joel :
 - [x] delete ```menu_reply.py```
 - [x] rename ```peribahasa.py``` to ```configuration.py``` atau bisa juga pilhan dibawah:
    - ```telebot_configuration.py```
    - ```data.py```
    - - [x] ```telebot_data.py```
    - ```config.py```
- [x] rebase all code from ```menu_reply.py``` to ```peribahasa.py``` yang sudah di rename atau namanya tetap
- [x] rebase all code from ```emojis.py``` to ```peribahasa.py``` yang sudah di rename atau namanya tetap

**Comment by slowy07** [comment]
> ## Update Feature
> * [x]  delete `menu_reply.py`
> * [x]  rename `peribahasa.py` to `configuration.py` atau bisa juga pilhan dibawah:
>   
>   * `telebot_configuration.py`
>   * `data.py`
>   * [x]  `telebot_data.py`
>   * `config.py`
> * [x]  rebase all code from `menu_reply.py` to `peribahasa.py` yang sudah di rename atau namanya tetap
> * [x]  rebase all code from `emojis.py` to `peribahasa.py` yang sudah di rename atau namanya tetap

buat pull request joe,terus link issue joe, punya kita kan #7 ah di markdown nnti kau buat linknya kyk gitu joe, contoh

```
<isi tentang deskripsi yang kau fixing joe>

[issue nomor 7](#7)
```

gitu joe nnti muncul dia yng link itu
